### ISSUE TITLE
Turn on Dart's strong mode

### ISSUE THREAD

**Issue by kseo** [fluidic/beaver#50]

**Comment by kseo** [comment]
We still have some errors.

ERROR: Couldn't infer type parameter 'V'; 'List<Map<String, Object>>' must be of type 'List<Map<String, String>>'. ([beaver_api] lib/src/beaver_api_base.dart:89)
ERROR: Target of URI doesn't exist: 'package:parsers/parsers.dart'. ([beaver_trigger_handler] lib/src/base.dart:4)
ERROR: Classes can only extend other classes. ([beaver_trigger_handler] lib/src/base.dart:180)
ERROR: Undefined class 'LanguageParsers'. ([beaver_trigger_handler] lib/src/base.dart:180)
ERROR: The method 'string' isn't defined for the class '_TriggerData'. ([beaver_trigger_handler] lib/src/base.dart:181)
ERROR: Undefined name 'dot'. ([beaver_trigger_handler] lib/src/base.dart:184)
ERROR: Undefined name 'identifier'. ([beaver_trigger_handler] lib/src/base.dart:184)
ERROR: Undefined name 'eof'. ([beaver_trigger_handler] lib/src/base.dart:186)
ERROR: Undefined name 'spaces'. ([beaver_trigger_handler] lib/src/base.dart:186)

**Comment by maniagoon** [comment]
ERROR: Couldn't infer type parameter 'V'; 'List>' must be of type 'List>'. ([beaver_api] lib/src/beaver_api_base.dart:89)

is fixed with 344c06d477764fe47f29b9eee22be0f628bd68a9.

The rest will be removed after doing "pub get".
